## Session #1 Homework 

In [1]:
!pip install wget
import wget
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = wget.download(url)
print(filename)

100% [..........................................................................] 1475504 / 1475504data (2).csv


In [2]:
filename

'data (2).csv'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [6]:
df.Make.unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

## Question 1
What's the average price of BMW cars in the dataset?

### Solution 1

In [7]:
bmw = df[df['Make']=='BMW']

In [8]:
bmw_avg_price = bmw['MSRP'].sum()/334

In [9]:
bmw_avg_price

61546.76347305389

### Solution 2

In [10]:
df[df.Make == 'BMW'].MSRP.mean()

61546.76347305389

### Solution 3

In [11]:
df.groupby('Make').MSRP.mean().round(3)

Make
Acura              34887.587
Alfa Romeo         61600.000
Aston Martin      197910.376
Audi               53452.113
BMW                61546.763
Bentley           247169.324
Bugatti          1757223.667
Buick              28206.612
Cadillac           56231.317
Chevrolet          28350.386
Chrysler           26722.963
Dodge              22390.059
FIAT               22670.242
Ferrari           238218.841
Ford               27399.267
GMC                30493.299
Genesis            46616.667
HUMMER             36464.412
Honda              26674.341
Hyundai            24597.036
Infiniti           42394.212
Kia                25310.173
Lamborghini       331567.308
Land Rover         67823.217
Lexus              47549.069
Lincoln            42839.829
Lotus              69188.276
Maserati          114207.707
Maybach           546221.875
Mazda              20039.383
McLaren           239805.000
Mercedes-Benz      71476.229
Mitsubishi         21240.535
Nissan             28583.432
Oldsmobil

## Question 2
Select a subset of cars after year 2015(inclusive,i.e2015 and afer). How many of them have missing values for Engine HP?

In [12]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

### Solution 1

In [13]:
ques_2 = df[df['Year'] >= 2015]

In [14]:
EHP_missing = ques_2['Engine HP'].isnull().sum()

In [15]:
EHP_missing

51

## Question 3
-  Calculate the average "Engine HP" in the dataset
-  Use the `fillna` method and to fill the missing values in "Engine HP" with the mean value from the previous step
-  Now, calculate the average of "Engine HP" again.
-  Has it changed?

Round both means before answering this questions. You can use the `round` function for that:

### Solution 1

### *Engine HP average before filling missing values*

In [16]:
mean_hp_before = df['Engine HP'].mean()

In [17]:
mean_hp_before

249.38607007176023

### *Filling missing values with previous mean*

In [18]:
df['Engine HP'].isna().sum()

69

In [19]:
df['Engine HP']=df['Engine HP'].fillna(mean_hp_before)

In [20]:
df['Engine HP'].isna().sum()

0

In [21]:
mean_hp_after = df['Engine HP'].mean()

In [22]:
mean_hp_after

249.38607007176

In [23]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


### Solution 2

In [24]:
df['Engine HP'].fillna(0).mean()

249.38607007176

## Question 4
-  Select all the "Rolls-Royce" cars from the dataset.
-  Select only columns "Engine HP","Engine Cylinders","highway MPG".
-  Now drop all duplicated rows using `drop_duplicates` method(you should get a dataframe with 7 rows).
-  Get the underlying NumPy array. Let's call it `X`.
-  Compute matrix-matrix multiplication between the transposed `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
-  Invert `XTX`.
-  What's the sum of all the elementsof the result?

## Solution 1

In [59]:
roro = df[df.Make=='Rolls-Royce'][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

In [60]:
roro

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [61]:
X = roro.values

In [62]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [63]:
XTX = X.T.dot(X)

In [64]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [65]:
XTX_inv=np.linalg.inv(XTX)

In [67]:
XTX_inv.sum()

0.032212320677486195

## Solution 2

df_rr=df[df.Make=='Rolls-Royce'][['Engine HP','Engine Cylinders','highway MPG']].drop_duplicates()

X = df_rr.values

X.T

XTX = X.T.dot(X)

XTX_inv = np.linalg.inv(XTX) 

XTX_inv

XTX_inv.sum()

## Question 5
- Create an array `y` with values `[1000,1100,900,1200,1000,850,1300]`.
- Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the resulr `w`.
- What's the value of the first element of `w`?

In [68]:
y= [1000,1100,900,1200,1000,850,1300]

In [76]:
w = XTX_inv.dot(X.T).dot(y)

In [77]:
w

array([ 0.19989598, 31.02612262, 31.65378877])